---
server:
  port: 8762
spring:
  profiles: dev  #开发环境
  application:
    name: config-client
foo: foo version 1111666

---
server:
  port: 8763
spring:
  profiles: test  #开发环境
  application:
    name: config-client
foo: foo version 1111666
