spring:
  profiles:
    active:
    - dev

---

server:
  port: 7001
spring:
  profiles: dev
  application:
    name: springcloud-test-config-eureka-client
eureka:
  instance:
    hostname: eureka7001.com
  client:
    register-with-eureka: false 
    fetch-registry: false  
    service-url:
      #单机 defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #  设置与Eureka Server交互的地址查询服务与注册服务都需要这个地址
      defaultZone: http://eureka7002.com:7002/eureka/



---

server:
  port: 7002
spring:
  profiles: test
  application: 
    name: springcloud-test-config-eureka-client
eureka:
  instance:
    hostname: eureka7002.com
  client:
    register-with-eureka: false
    fetch-registry: false 
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/